title = "Config"
version = 1.0

[broker] # this has 4 layers root -> qualifier -> name -> location. Could go down to 2 if needed.
broker = "127.0.0.1" # Mosquitto (MQTT) server
port = 1883
topic-root = 'carpark' #MS Teams Team
topic-qualifier = 'controller' #MS Teams channel
name= 'parking-lot' #Channel conversation/discussion
location = 'MOO' #location of the discussion
is_stuff = False
# sensor = "sensor 1"

[MOO]
name = 'Moondalup City Square Parking'
total-spaces = 192
total-cars = 0

[sensor1]
name = "entry"

# have sections which are listed in brackets
# Adrian encountered an error because he had sections - consider making new toml file for each section if errors occur