title = "Config"
version = 1.0
broker = "127.0.0.1"
port = 1883
topic-root = 'carpark'
topic-qualifier = 'controller'
name= 'parking-lot'
location = 'MOO'
is_stuff = False

[MOO]
name = 'Moondalup City Square Parking'
total-spaces = 192
total-cars = 0